### PR TITLE
Resolving issue 2 , changed some translations in NeedABreak.en.xlf

### PR DESCRIPTION
**Pull request by Armdt**
resolving https://github.com/bNobo/needabreak/issues/2 changed translations with these IDs :
"ajuster_le_delai", "explications",  "il_est_l_heure", "Less_than_a_minute_before_locking", "minutes_before_locking", "one_minute_before_locking"

### CODE REVIEW

**Comment by bNobo** [comment]
Hi, I am not sure about the term "work hour" because it does not represent a duration but a specific time in the day. Buttons in the application are showing durations : it corresponds to the delay after which the screen will be automatically locked.

**Comment by Armdt** [comment]
Hi dear @bNobo , it's good point , I work on this issue more and improve it, please feel free for ask for  any other changes or comments.

**Comment by bNobo** [comment]
Thank you for you help @Armdt !

**Comment by Armdt** [comment]
Hi dear @bNobo , it's good point , I work on this issue more and improve it, please feel free for ask for  any other changes or comments.

**Comment by bNobo** [comment]
Hi @Armdt, you're absolutely right when you want to replace the term "time frame" with something else. "time frame" is not the right word. I've made some research and it seems to me that the good term would be "wait". For instance instead of "Adjust the time frame", we would have "Adjust the wait". What do you think about that ?

**Comment by Armdt** [comment]
Hi @bNobo , I agree "time frame" is not the right word, and "adjust the wait" or "adjust the wait time" are right in this context.
also i noticed the order in description of time duration is reverse. (I think 45 minutes should be low intensive work duration and 120 minutes should be very intensive work and so on) Is it right?

**Comment by bNobo** [comment]
Hi @Armdt, no it should not be reversed : when you work intensively you need to break more frequently because intensive work cause more tensions.

**Comment by Armdt** [comment]
@bNobo So when we want to work very intensive it's good to take break after 45 minutes, am I getting it right?

**Comment by bNobo** [comment]
Yes, that's it!

Le ven. 20 mars 2020 à 18:30, Armin Irandoust <notifications@github.com> a
écrit :

**Comment by Armdt** [comment]
Hi @bNobo i just added some commits, please feel free for any changes.

**Comment by bNobo** [comment]
Hi @Armdt, translations seems to be OK now, I'm going to merge your branch. For your information, you don't need to update .resx files, they are automatically updated by Multilingual App Toolkit.

Thanks for your help !

**Pull request merged**
